server:
  port: 8090
  servlet:
    context-path: /flowable

spring:
  application:
    name: loan24h-flowable-service
  #  liquibase:
  #    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flowable
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

flowable:
  database-schema-update: true
  check-process-definitions: true
  history-level: full

